name: Deploy to AWS Lambda
on:
  push:
    branches:
      - main  # Cambia esto por el nombre de tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Cambia esto por la versión de Python que necesites

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Si tienes un archivo de requerimientos para tu Lambda

      - name: Zip code
        run: |
          zip -r codigo.zip . -x '*.git*'  # Comprime el código excluyendo archivos de Git
      
      - name: Install AWS CLI
        run: |
          sudo apt-get install python3-pip
          pip3 install --upgrade pip
          pip3 install awscli
      - name: Update AWS CLI
        run: |
            sudo apt-get update
            sudo apt-get install --only-upgrade awscli -y
        

      - name: Deploy to Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_REGION: 'us-east-1'  # Cambia esto por tu región AWS
        run: |
          aws lambda update-function-code --function-name lambda_python --zip-file fileb://codigo.zip
